# 机器人硬件索引配置
robot:
  name: "Agilex_Cobot_Magic"
  # 手臂索引定义 [start, end]
  # 左闭右开
  arms:
    right:
      move: [8, 11]     # 对应 qpos 的索引
      rotate: [11, 14]
      gripper: 7
    left:
      move: [22, 25]
      rotate: [25, 28]
      gripper: 21

# 运动学计算参数
kinematics:
  fps: 30
  num_samples: 32
  mimic_gripper: true    # 是否将 1 维夹爪映射为 2 维

# 物理切分参数 (Pelt / LSTM)
segmentation:
  use_lstm: true
  adaptive: true